version: "3"
services:
  server:
    build: ./server
    ports:
      - "8000:8000"
    volumes:
      - ./server/app:/app
 
  client:
    build: ./client
    ports:
      - "8000:8000"
    volumes:
      - ./client/app:/app
